---

- name: rstudio | install apt package
  tags:
    - package
  apt:
    deb: 'https://download2.rstudio.org/rstudio-server-{{ rstudio_ver }}-{{ ansible_architecture | replace("x86_64", "amd64") }}.deb'

- name: rstudio | user group
  tags:
    - user
  group:
    name: "{{ rstudio_group }}"

- name: rstudio | user
  tags:
    - user
  user:
    name: "{{ rstudio_user }}"
    group: "{{ rstudio_group }}"
    password: "{{ rstudio_passwd | password_hash('sha512') }}"

- name: rstudio | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rstudio/{{ item }}"
  with_items:
    - rserver.conf
    - rsession.conf
  notify: restart rstudio

- name: rstudio | nginx site
  tags:
    - site
  template:
    src: "{{ item }}.nginx.j2"
    dest: /etc/nginx/sites-available/{{ item }}
  with_items:
    - rstudio
  notify: restart rstudio

- name: rstudio | enable nginx site
  tags:
    - site
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items:
    - rstudio
  notify: restart rstudio

- name: rstudio | service
  tags:
    - service
  service:
    name: rstudio-server
    state: started
    enabled: yes

