---
burp_version: 2.1.18

burp_server: 127.0.0.1
burp_port: 4971
burp_status_port: 4972

burpui_host: burp.example.com
burpui_localport: 5000

burp_user: burp
burp_data_dir: /var/burp
burp_pid_dir: /var/run/burp
burp_ca_name: burp
burp_server_CN: burp

burp_restore_clients: []

burp_pw: ''

burp_offsite: '/mnt/offsite'
